trigger:
  - main
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  webAppName: 'my-angular-app-dhiraj'
 
stages:
- stage: Build
  jobs:
  - job: BuildAngularApp
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: 'Install Node.js'
 
    - script: |
        npm install
        npm run build -- --configuration production
      displayName: 'npm install and build'
 
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/my-angular-app/browser'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
      displayName: 'Archive build output'
 
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish artifact'
 
- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployWebApp
    environment: 'production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadSecureFile@1
            name: publishProfile
            inputs:
              secureFile: 'my-angular-app-dhiraj.PublishSettings'
            displayName: 'Download publish profile'
 
          - task: AzureWebApp@1
            inputs:
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              publishProfilePath: '$(publishProfile.secureFilePath)'
            displayName: 'Deploy to Azure Web App'
 