trigger:
  - main
 
pool:
  vmImage: 'ubuntu-latest'
 
stages:
- stage: Build
  jobs:
  - job: BuildAngularApp
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: 'Install Node.js'
 
    - script: |
        npm install
        npm run build -- --configuration production
        mkdir deploy
        cp -r dist deploy/dist
        cp server.js deploy/
        cp package.json deploy/
        cp package-lock.json deploy/
        cd deploy
        npm install --omit=dev
      displayName: 'npm install, build, and prepare deploy package'
 
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/deploy'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
      displayName: 'Archive deploy package'
 
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish artifact'
 
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployWebApp
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
      displayName: 'Download artifact'
 
    - script: |
        curl -4 -X POST \
          -u "$(DeployUsername):$(DeployPasswordd)" \
          --data-binary @"$(System.ArtifactsDirectory)/drop/$(Build.BuildId).zip" \
          "https://my-angular-app-dhiraj-baenendvhebdeaba.scm.centralindia-01.azurewebsites.net/api/zipdeploy"
      displayName: 'Deploy via Kudu ZipDeploy'
 